word_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'welcome#index'

  get '/user/words/search' => 'words#user_word'
  post '/words/:id' => 'words#show'
  get '/words/search' => 'words#search_word'
  post '/user/words' => 'words#create'
  get '/user/words' => 'words#index'

  namespace :api do
  	resources :words
  	resource :user
  end		
end

word_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :words
end

word_app/app/models/word.rb
class Word < ActiveRecord::Base
	belongs_to :user
end

word_app/app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
    respond_to :json

    def index
        users = Users.all
        render json: users
    end

    def create
        user = User.create(user_params)
        render json: user
    end

    def show
        user = User.find(current_user.id)
        render json: user
    end

    def update 
        user = User.find(current_user.id)
        User.update(user_params)
        render json: user
    end

    def destroy
        user = User.find(current_user.id)
        User.destroy
        render json: "user destroyed"
    end

    private

    def user_params
        params.require(:user).permit(:user)
    end
end    

word_app/app/controllers/api/words_controller.rb
class Api::WordsController < ApplicationController
    respond_to :json

    def index
        words = Word.all
        render json: words
    end

    def create
        word = Word.create(word_params)
        render json: word
    end

    def show
        word = Word.find(params[:id])
        render json: word
    end

    def update 
        word = Word.find(params[:id])
        word.update(word_params)
        render json: word
    end

    def destroy
        word = Word.find(params[:id])
        word.destroy
        render json: "word destroyed"
    end

    private

    def word_params
        params.require(:word).permit(:word)
    end
end    

word_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

word_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	
end

word_app/app/controllers/words_controller.rb
require'json'
require 'uri'

class WordsController < ApplicationController

	def index
	 if current_user
	    @words = Word.where(user_id:current_user)
		@user = current_user
		@word = @user.words
		render:index
	 else
      	redirect_to login_path
    end
	end

	def user_word
		@word = current_user.words.build
		@word_search = params[:word]
		base = "https://wordsapiv1.p.mashape.com/words/"
		query = URI.encode_www_form("query" => @word_search)
		mashape = base + @word_search

		@response = HTTParty.get(mashape,
  			headers:{
   				"X-Mashape-Key" => ENV["WORD_API"],
    			"Accept" => "application/json"
  			})
  		@body = @response["results"]
		@def_body = @body.map{|x| x.values[1] +'. '+ x.values[0]}
			render :show
	end

	def show
		@word = Word.find(params[:id])
		render :user_show
	end
	
	def search_word
		@word = current_user.words.build
		@word_search = params[:word]
		base = "https://wordsapiv1.p.mashape.com/words/"
		query = URI.encode_www_form("query" => @word_search)
		mashape = base + @word_search

		@response = HTTParty.get(mashape,
  			headers:{
   				"X-Mashape-Key" => ENV["WORD_API"],
    			"Accept" => "application/json"
  			})
  		@body = @response["results"]	
		@def_body = @body.map{|x| x.values[1] +'. '+ x.values[0]}
		@syn = @body.map{|s| s.values[2]}
		@sen = @body.map{|e| e.values[5]}
			render :show
	end

	def edit
	end

	def create
		@post = current_user.words.build(word_params)
		@word = Word.create(word_params)
		redirect_to root_path
	end

	private

	def word_params
		params.require(:word).permit(:word, :user_id)
	end


end

word_app/app/helpers/application_helper.rb
module ApplicationHelper
end

word_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WordApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Special+Elite:400' rel='stylesheet' type='text/css'>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

word_app/app/views/welcome/index.html.erb
<!doctype html>

<html lang="en">  
    <head>
        <meta charset="UTF8">
        <title>word.</title>


        <!-- <link href='css/main.css' rel='stylesheet' type='text/css'> -->
    </head>
    <body>
    	<header id="container">
            <h1 class="main_title"><%= link_to "word.", root_path %></h1>
    <nav>
        <% if user_signed_in? %>
            <%= link_to "my words", user_words_path(current_user) %> | 
            <%= link_to "log out", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to "log in", new_user_session_path %> |
            <%= link_to "sign up", new_user_registration_path %>
        <% end %>
    </nav></br></br></br>

    <div class="word-search">
        <%= form_tag words_search_path, method: "get" do %>
            <%= text_field_tag(:word, nil, placeholder: "PUT WORD HERE", ) %>
            <input type="submit">
        <% end %>
    </div>
    
        </header>
        </div></br></br></br></br>
        <!-- <div id="word_of_the_day">
                <h2 class="random_word">traversing</h2>
                <h4>v. Present participle of traverse.</h4>
                <h4>adj. Adjustable laterally; having a lateral motion, or a swinging motion; adapted for giving lateral motion.</h4>
                <h4>n. The motion of the cutting tool in a machine: strictly, it denotes the motion across the work, but is popularly extended to mean the same as ‘travel’ (of the tool or its carriage). Originally, it was the horizontal angular motion of a gun-carriage.</h4>
        </div> -->

    </body>
</html> 

word_app/app/views/words/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>word.</title>
</head>
<body>
<header><%= link_to "word.", root_path %></header>	
	<div class="container">
		<div type="text/template" id="word-template">
        	<div id="word-front">
        		<div id="word-paper">
        			<div id="word-list">
        				<h1 class="list-title">my words</h1>

						<%@words.each do |p|%>
						<%= link_to p.word, user_words_search_path + "?word=" + p.word, method: :get, word: "hi"%>
    
						</br></br>
        				<%end%>
        			</div>
        		</div>
      		</div>
		</div> 
	</div>
</body>
</html>

word_app/app/views/words/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>word.</title>
</head>
<body>
<div class="go_home"><%= link_to "word.", root_path %></div>  
    <div class="container">
        <div class="shadow">
            <div id="word-front">
                <div id="word-paper">
                    <div id="word-target">
                        <ul>
                        <h1 id="wordname"><%=@word_search%></h1>
                            <li><% @def_body.each do |y|%>
                            <%= y %></br></br>
                            <%end%>
                            </li>
            <div class="save"><%= form_for @word,url: {action: "create"} do |f|%>
                            <%= f.hidden_field :word, :value => @word_search %>
                            <%= f.hidden_field :user_id, :value => current_user.id.to_s %>
                            <%= f.submit "save word."%>
                            <%end%>
                        </div>  
                    </div>
                    <div id="def-paper">
        				<div id="def-target">
        				</div>
        			</div>
        		</div>
      		</div>
        </div>
	</div>
</body>
</html>